"""
IAM Action Mapping Table
Maps (service, boto3_method) -> IAM action string.

Maintenance rules:
- Add entries when a real repo exposes a gap (unknown:unknown in gate output)
- Never guess — if mapping missing, resolver returns confidence=low
- Source: AWS IAM policy generator + manual correction against real repos

Gap log (add entry when fixed):
  2026-07-25: added sns, sqs, ses, events, ssm, bedrock-agent-runtime
  2026-07-25: added dynamodb resource API (Table method)
  2026-07-28: added textract, support, cloudformation
  2026-07-28: added stepfunctions send_task_*, logs export tasks, cognito list_user_pool_clients
  2026-07-28: skip lambda.get_waiter (SDK utility, not IAM action)
  2026-07-28: skip bedrock-agentcore-control (too new, no public IAM docs)
"""

IAM_ACTION_MAP: dict[str, dict[str, str]] = {
    "s3": {
        "get_object":                           "s3:GetObject",
        "put_object":                           "s3:PutObject",
        "delete_object":                        "s3:DeleteObject",
        "delete_objects":                       "s3:DeleteObject",
        "list_objects":                         "s3:ListBucket",
        "list_objects_v2":                      "s3:ListBucket",
        "head_object":                          "s3:GetObject",
        "copy_object":                          "s3:CopyObject",
        "create_bucket":                        "s3:CreateBucket",
        "delete_bucket":                        "s3:DeleteBucket",
        "get_bucket_policy":                    "s3:GetBucketPolicy",
        "put_bucket_policy":                    "s3:PutBucketPolicy",
        "delete_bucket_policy":                 "s3:DeleteBucketPolicy",
        "get_bucket_acl":                       "s3:GetBucketAcl",
        "put_bucket_acl":                       "s3:PutBucketAcl",
        "upload_file":                          "s3:PutObject",
        "download_file":                        "s3:GetObject",
        "generate_presigned_url":               "s3:GetObject",
        "list_buckets":                         "s3:ListAllMyBuckets",
        "get_bucket_versioning":                "s3:GetBucketVersioning",
        "put_bucket_versioning":                "s3:PutBucketVersioning",
        "get_bucket_encryption":                "s3:GetEncryptionConfiguration",
        "put_bucket_encryption":                "s3:PutEncryptionConfiguration",
    },
    "dynamodb": {
        # Client API
        "get_item":                             "dynamodb:GetItem",
        "put_item":                             "dynamodb:PutItem",
        "delete_item":                          "dynamodb:DeleteItem",
        "update_item":                          "dynamodb:UpdateItem",
        "query":                                "dynamodb:Query",
        "scan":                                 "dynamodb:Scan",
        "batch_get_item":                       "dynamodb:BatchGetItem",
        "batch_write_item":                     "dynamodb:BatchWriteItem",
        "create_table":                         "dynamodb:CreateTable",
        "delete_table":                         "dynamodb:DeleteTable",
        "describe_table":                       "dynamodb:DescribeTable",
        "list_tables":                          "dynamodb:ListTables",
        "transact_get_items":                   "dynamodb:TransactGetItems",
        "transact_write_items":                 "dynamodb:TransactWriteItems",
        "update_table":                         "dynamodb:UpdateTable",
        # Resource API
        "table":                                "dynamodb:DescribeTable",
    },
    "lambda": {
        "invoke":                               "lambda:InvokeFunction",
        "create_function":                      "lambda:CreateFunction",
        "delete_function":                      "lambda:DeleteFunction",
        "update_function_code":                 "lambda:UpdateFunctionCode",
        "update_function_configuration":        "lambda:UpdateFunctionConfiguration",
        "get_function":                         "lambda:GetFunction",
        "list_functions":                       "lambda:ListFunctions",
        "add_permission":                       "lambda:AddPermission",
        "remove_permission":                    "lambda:RemovePermission",
        "create_event_source_mapping":          "lambda:CreateEventSourceMapping",
        "delete_event_source_mapping":          "lambda:DeleteEventSourceMapping",
        "list_event_source_mappings":           "lambda:ListEventSourceMappings",
        # get_waiter is an SDK utility method, not an IAM action — intentionally omitted
    },
    "iam": {
        "create_role":                          "iam:CreateRole",
        "delete_role":                          "iam:DeleteRole",
        "get_role":                             "iam:GetRole",
        "list_roles":                           "iam:ListRoles",
        "attach_role_policy":                   "iam:AttachRolePolicy",
        "detach_role_policy":                   "iam:DetachRolePolicy",
        "create_policy":                        "iam:CreatePolicy",
        "delete_policy":                        "iam:DeletePolicy",
        "get_policy":                           "iam:GetPolicy",
        "list_policies":                        "iam:ListPolicies",
        "create_user":                          "iam:CreateUser",
        "delete_user":                          "iam:DeleteUser",
        "create_access_key":                    "iam:CreateAccessKey",
        "delete_access_key":                    "iam:DeleteAccessKey",
        "list_users":                           "iam:ListUsers",
        "get_user":                             "iam:GetUser",
        "put_role_policy":                      "iam:PutRolePolicy",
        "delete_role_policy":                   "iam:DeleteRolePolicy",
        "get_role_policy":                      "iam:GetRolePolicy",
    },
    "kms": {
        "decrypt":                              "kms:Decrypt",
        "encrypt":                              "kms:Encrypt",
        "generate_data_key":                    "kms:GenerateDataKey",
        "generate_data_key_without_plaintext":  "kms:GenerateDataKeyWithoutPlaintext",
        "describe_key":                         "kms:DescribeKey",
        "list_keys":                            "kms:ListKeys",
        "create_key":                           "kms:CreateKey",
        "schedule_key_deletion":                "kms:ScheduleKeyDeletion",
        "sign":                                 "kms:Sign",
        "verify":                               "kms:Verify",
        "get_key_policy":                       "kms:GetKeyPolicy",
        "put_key_policy":                       "kms:PutKeyPolicy",
        "enable_key":                           "kms:EnableKey",
        "disable_key":                          "kms:DisableKey",
    },
    "sts": {
        "assume_role":                          "sts:AssumeRole",
        "get_caller_identity":                  "sts:GetCallerIdentity",
        "get_session_token":                    "sts:GetSessionToken",
        "assume_role_with_web_identity":        "sts:AssumeRoleWithWebIdentity",
    },
    "sns": {
        "publish":                              "sns:Publish",
        "subscribe":                            "sns:Subscribe",
        "unsubscribe":                          "sns:Unsubscribe",
        "create_topic":                         "sns:CreateTopic",
        "delete_topic":                         "sns:DeleteTopic",
        "list_topics":                          "sns:ListTopics",
        "list_subscriptions":                   "sns:ListSubscriptions",
        "get_topic_attributes":                 "sns:GetTopicAttributes",
        "set_topic_attributes":                 "sns:SetTopicAttributes",
        "list_subscriptions_by_topic":          "sns:ListSubscriptionsByTopic",
        "confirm_subscription":                 "sns:ConfirmSubscription",
    },
    "sqs": {
        "send_message":                         "sqs:SendMessage",
        "receive_message":                      "sqs:ReceiveMessage",
        "delete_message":                       "sqs:DeleteMessage",
        "delete_message_batch":                 "sqs:DeleteMessageBatch",
        "send_message_batch":                   "sqs:SendMessageBatch",
        "create_queue":                         "sqs:CreateQueue",
        "delete_queue":                         "sqs:DeleteQueue",
        "get_queue_url":                        "sqs:GetQueueUrl",
        "get_queue_attributes":                 "sqs:GetQueueAttributes",
        "set_queue_attributes":                 "sqs:SetQueueAttributes",
        "list_queues":                          "sqs:ListQueues",
        "purge_queue":                          "sqs:PurgeQueue",
        "change_message_visibility":            "sqs:ChangeMessageVisibility",
        "change_message_visibility_batch":      "sqs:ChangeMessageVisibility",
    },
    "ses": {
        "send_email":                           "ses:SendEmail",
        "send_raw_email":                       "ses:SendRawEmail",
        "send_templated_email":                 "ses:SendTemplatedEmail",
        "send_bulk_templated_email":            "ses:SendBulkTemplatedEmail",
        "create_template":                      "ses:CreateTemplate",
        "delete_template":                      "ses:DeleteTemplate",
        "list_templates":                       "ses:ListTemplates",
        "verify_email_identity":                "ses:VerifyEmailIdentity",
        "list_identities":                      "ses:ListIdentities",
        "get_send_quota":                       "ses:GetSendQuota",
        "get_send_statistics":                  "ses:GetSendStatistics",
    },
    "sesv2": {
        "send_email":                           "ses:SendEmail",
        "create_contact":                       "ses:CreateContact",
        "delete_contact":                       "ses:DeleteContact",
        "get_contact":                          "ses:GetContact",
        "list_contacts":                        "ses:ListContacts",
        "put_account_sending_attributes":       "ses:PutAccountSendingAttributes",
    },
    "events": {
        "put_events":                           "events:PutEvents",
        "put_rule":                             "events:PutRule",
        "delete_rule":                          "events:DeleteRule",
        "put_targets":                          "events:PutTargets",
        "remove_targets":                       "events:RemoveTargets",
        "list_rules":                           "events:ListRules",
        "describe_rule":                        "events:DescribeRule",
        "enable_rule":                          "events:EnableRule",
        "disable_rule":                         "events:DisableRule",
        "list_targets_by_rule":                 "events:ListTargetsByRule",
    },
    "ssm": {
        "get_parameter":                        "ssm:GetParameter",
        "get_parameters":                       "ssm:GetParameters",
        "get_parameters_by_path":               "ssm:GetParametersByPath",
        "put_parameter":                        "ssm:PutParameter",
        "delete_parameter":                     "ssm:DeleteParameter",
        "delete_parameters":                    "ssm:DeleteParameters",
        "describe_parameters":                  "ssm:DescribeParameters",
        "get_parameter_history":                "ssm:GetParameterHistory",
        "send_command":                         "ssm:SendCommand",
        "list_commands":                        "ssm:ListCommands",
        "get_command_invocation":               "ssm:GetCommandInvocation",
        "start_session":                        "ssm:StartSession",
        "terminate_session":                    "ssm:TerminateSession",
    },
    "secretsmanager": {
        "get_secret_value":                     "secretsmanager:GetSecretValue",
        "create_secret":                        "secretsmanager:CreateSecret",
        "delete_secret":                        "secretsmanager:DeleteSecret",
        "update_secret":                        "secretsmanager:UpdateSecret",
        "list_secrets":                         "secretsmanager:ListSecrets",
        "describe_secret":                      "secretsmanager:DescribeSecret",
        "put_secret_value":                     "secretsmanager:PutSecretValue",
        "rotate_secret":                        "secretsmanager:RotateSecret",
        "tag_resource":                         "secretsmanager:TagResource",
        "untag_resource":                       "secretsmanager:UntagResource",
        "restore_secret":                       "secretsmanager:RestoreSecret",
    },
    "bedrock-runtime": {
        "invoke_model":                         "bedrock:InvokeModel",
        "invoke_model_with_response_stream":    "bedrock:InvokeModelWithResponseStream",
        "converse":                             "bedrock:InvokeModel",
        "converse_stream":                      "bedrock:InvokeModelWithResponseStream",
    },
    "bedrock": {
        "invoke_model":                         "bedrock:InvokeModel",
        "invoke_model_with_response_stream":    "bedrock:InvokeModelWithResponseStream",
        "list_foundation_models":               "bedrock:ListFoundationModels",
        "get_foundation_model":                 "bedrock:GetFoundationModel",
    },
    "bedrock-agent-runtime": {
        "invoke_agent":                         "bedrock:InvokeAgent",
        "retrieve":                             "bedrock:Retrieve",
        "retrieve_and_generate":                "bedrock:RetrieveAndGenerate",
    },
    "bedrock-agent": {
        "create_agent":                         "bedrock:CreateAgent",
        "delete_agent":                         "bedrock:DeleteAgent",
        "get_agent":                            "bedrock:GetAgent",
        "list_agents":                          "bedrock:ListAgents",
        "prepare_agent":                        "bedrock:PrepareAgent",
        "create_knowledge_base":                "bedrock:CreateKnowledgeBase",
        "delete_knowledge_base":                "bedrock:DeleteKnowledgeBase",
        "associate_agent_knowledge_base":       "bedrock:AssociateAgentKnowledgeBase",
    },
    "stepfunctions": {
        "start_execution":                      "states:StartExecution",
        "stop_execution":                       "states:StopExecution",
        "describe_execution":                   "states:DescribeExecution",
        "list_executions":                      "states:ListExecutions",
        "get_execution_history":                "states:GetExecutionHistory",
        "create_state_machine":                 "states:CreateStateMachine",
        "delete_state_machine":                 "states:DeleteStateMachine",
        "list_state_machines":                  "states:ListStateMachines",
        "describe_state_machine":               "states:DescribeStateMachine",
        "update_state_machine":                 "states:UpdateStateMachine",
        "start_sync_execution":                 "states:StartSyncExecution",
        "send_task_success":                    "states:SendTaskSuccess",
        "send_task_failure":                    "states:SendTaskFailure",
        "send_task_heartbeat":                  "states:SendTaskHeartbeat",
    },
    "cloudwatch": {
        "put_metric_data":                      "cloudwatch:PutMetricData",
        "get_metric_data":                      "cloudwatch:GetMetricData",
        "get_metric_statistics":                "cloudwatch:GetMetricStatistics",
        "list_metrics":                         "cloudwatch:ListMetrics",
        "put_metric_alarm":                     "cloudwatch:PutMetricAlarm",
        "delete_alarms":                        "cloudwatch:DeleteAlarms",
        "describe_alarms":                      "cloudwatch:DescribeAlarms",
        "enable_alarm_actions":                 "cloudwatch:EnableAlarmActions",
        "disable_alarm_actions":                "cloudwatch:DisableAlarmActions",
    },
    "logs": {
        "create_log_group":                     "logs:CreateLogGroup",
        "create_log_stream":                    "logs:CreateLogStream",
        "put_log_events":                       "logs:PutLogEvents",
        "get_log_events":                       "logs:GetLogEvents",
        "describe_log_groups":                  "logs:DescribeLogGroups",
        "describe_log_streams":                 "logs:DescribeLogStreams",
        "filter_log_events":                    "logs:FilterLogEvents",
        "delete_log_group":                     "logs:DeleteLogGroup",
        "delete_log_stream":                    "logs:DeleteLogStream",
        "start_query":                          "logs:StartQuery",
        "get_query_results":                    "logs:GetQueryResults",
        "create_export_task":                   "logs:CreateExportTask",
        "describe_export_tasks":                "logs:DescribeExportTasks",
    },
    "ec2": {
        "describe_instances":                   "ec2:DescribeInstances",
        "start_instances":                      "ec2:StartInstances",
        "stop_instances":                       "ec2:StopInstances",
        "terminate_instances":                  "ec2:TerminateInstances",
        "describe_security_groups":             "ec2:DescribeSecurityGroups",
        "create_security_group":                "ec2:CreateSecurityGroup",
        "delete_security_group":                "ec2:DeleteSecurityGroup",
        "describe_vpcs":                        "ec2:DescribeVpcs",
        "describe_subnets":                     "ec2:DescribeSubnets",
        "describe_images":                      "ec2:DescribeImages",
        "run_instances":                        "ec2:RunInstances",
        "create_tags":                          "ec2:CreateTags",
        "delete_tags":                          "ec2:DeleteTags",
    },
    "rds": {
        "describe_db_instances":                "rds:DescribeDBInstances",
        "create_db_instance":                   "rds:CreateDBInstance",
        "delete_db_instance":                   "rds:DeleteDBInstance",
        "start_db_instance":                    "rds:StartDBInstance",
        "stop_db_instance":                     "rds:StopDBInstance",
        "describe_db_clusters":                 "rds:DescribeDBClusters",
        "create_db_snapshot":                   "rds:CreateDBSnapshot",
        "delete_db_snapshot":                   "rds:DeleteDBSnapshot",
        "describe_db_snapshots":                "rds:DescribeDBSnapshots",
        "restore_db_instance_from_db_snapshot": "rds:RestoreDBInstanceFromDBSnapshot",
        "modify_db_instance":                   "rds:ModifyDBInstance",
    },
    "cognito-idp": {
        "admin_create_user":                    "cognito-idp:AdminCreateUser",
        "admin_delete_user":                    "cognito-idp:AdminDeleteUser",
        "admin_get_user":                       "cognito-idp:AdminGetUser",
        "list_users":                           "cognito-idp:ListUsers",
        "list_user_pool_clients":               "cognito-idp:ListUserPoolClients",
        "initiate_auth":                        "cognito-idp:InitiateAuth",
        "respond_to_auth_challenge":            "cognito-idp:RespondToAuthChallenge",
        "sign_up":                              "cognito-idp:SignUp",
        "confirm_sign_up":                      "cognito-idp:ConfirmSignUp",
        "forgot_password":                      "cognito-idp:ForgotPassword",
        "confirm_forgot_password":              "cognito-idp:ConfirmForgotPassword",
        "admin_set_user_password":              "cognito-idp:AdminSetUserPassword",
        "admin_initiate_auth":                  "cognito-idp:AdminInitiateAuth",
        "global_sign_out":                      "cognito-idp:GlobalSignOut",
        "change_password":                      "cognito-idp:ChangePassword",
    },
    "opensearch": {
        "index":                                "es:ESHttpPut",
        "search":                               "es:ESHttpGet",
        "delete":                               "es:ESHttpDelete",
        "create":                               "es:ESHttpPut",
    },
    "firehose": {
        "put_record":                           "firehose:PutRecord",
        "put_record_batch":                     "firehose:PutRecordBatch",
        "create_delivery_stream":               "firehose:CreateDeliveryStream",
        "delete_delivery_stream":               "firehose:DeleteDeliveryStream",
        "describe_delivery_stream":             "firehose:DescribeDeliveryStream",
        "list_delivery_streams":                "firehose:ListDeliveryStreams",
        "update_destination":                   "firehose:UpdateDestination",
    },
    "kinesis": {
        "put_record":                           "kinesis:PutRecord",
        "put_records":                          "kinesis:PutRecords",
        "get_records":                          "kinesis:GetRecords",
        "get_shard_iterator":                   "kinesis:GetShardIterator",
        "describe_stream":                      "kinesis:DescribeStream",
        "list_streams":                         "kinesis:ListStreams",
        "create_stream":                        "kinesis:CreateStream",
        "delete_stream":                        "kinesis:DeleteStream",
        "merge_shards":                         "kinesis:MergeShards",
        "split_shard":                          "kinesis:SplitShard",
    },
    "textract": {
        "detect_document_text":                 "textract:DetectDocumentText",
        "analyze_document":                     "textract:AnalyzeDocument",
        "start_document_text_detection":        "textract:StartDocumentTextDetection",
        "get_document_text_detection":          "textract:GetDocumentTextDetection",
        "start_document_analysis":              "textract:StartDocumentAnalysis",
        "get_document_analysis":                "textract:GetDocumentAnalysis",
    },
    "support": {
        "describe_trusted_advisor_checks":          "support:DescribeTrustedAdvisorChecks",
        "describe_trusted_advisor_check_result":    "support:DescribeTrustedAdvisorCheckResult",
        "refresh_trusted_advisor_check":            "support:RefreshTrustedAdvisorCheck",
        "describe_cases":                           "support:DescribeCases",
        "create_case":                              "support:CreateCase",
        "add_communication_to_case":                "support:AddCommunicationToCase",
        "resolve_case":                             "support:ResolveCase",
    },
    "cloudformation": {
        "describe_stacks":                          "cloudformation:DescribeStacks",
        "create_stack":                             "cloudformation:CreateStack",
        "update_stack":                             "cloudformation:UpdateStack",
        "delete_stack":                             "cloudformation:DeleteStack",
        "describe_stack_events":                    "cloudformation:DescribeStackEvents",
        "describe_stack_resources":                 "cloudformation:DescribeStackResources",
        "list_stacks":                              "cloudformation:ListStacks",
        "get_template":                             "cloudformation:GetTemplate",
        "validate_template":                        "cloudformation:ValidateTemplate",
        "create_change_set":                        "cloudformation:CreateChangeSet",
        "execute_change_set":                       "cloudformation:ExecuteChangeSet",
        "describe_change_set":                      "cloudformation:DescribeChangeSet",
    },
}


def resolve_iam_action(service: str, method: str) -> tuple[str, str]:
    """
    Resolves a boto3 method call to its IAM action string.

    Returns:
        (action_iam, confidence)
        ("s3:GetObject", "high")      — known mapping
        ("unknown:unknown", "low")    — missing, never guesses

    Rule: wrong mapping is worse than no mapping.
    """
    service_map = IAM_ACTION_MAP.get(service.lower())
    if not service_map:
        return ("unknown:unknown", "low")

    action = service_map.get(method.lower())
    if not action:
        return ("unknown:unknown", "low")

    return (action, "high")